//user login
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESSED = 'USER_LOGIN_SUCCESSED';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';

//user register
export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_SUCCESSED = 'USER_REGISTER_SUCCESSED';
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';